version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "4040:4040"
    volumes:
      - .:/app
      - /app/node_modules # 排除 node_modules
      - /app/.angular # 排除 Angular 快取
    environment:
      - NODE_ENV=development
    # command: npm start
    command: tail -f /dev/null
    tty: true
